// Mocks generated by Mockito 5.0.16 from annotations
// in tourbillauth/test/user_selector_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;
import 'package:tourbillauth/app_user.dart' as _i3;
import 'package:tourbillauth/user_selector_model.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [UserSelectorModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserSelectorModel extends _i1.Mock implements _i2.UserSelectorModel {
  MockUserSelectorModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.AppUser> findUsers(String? query) =>
      (super.noSuchMethod(Invocation.method(#findUsers, [query]),
          returnValue: <_i3.AppUser>[]) as List<_i3.AppUser>);
  @override
  String toString() => super.toString();
}
